export * from './Icons/Icons'
export { Header }  from './Header/Header'
export { Hero } from './Hero/Hero'
export { Meaning } from './Meaning/Meaning'
export { Advices } from './Advices/Advices'
export { Limitations } from './Limitations/Limitations'